/**
 * One-click "Remind me" handler — wired into the email-reply magic-link.
 *
 * Flow:
 *   1. Customer forwards a policy to review@rightoffer.in
 *   2. Audit reply lands with a "→ Remind me before this expires" link
 *   3. They click → this route fires
 *   4. We verify the HMAC token, create (or activate) a RenewalSubscription
 *      for the linked parsedPolicyId, email-only channels
 *   5. Redirect to /reminders/done — a thin confirmation page
 *
 * The token is generated by buildRemindMeUrl() in email-token.ts. Its
 * payload subject packs `email|parsedPolicyId` so we don't need a
 * session lookup. 30-day expiry on the token — customers who find the
 * audit weeks later can still subscribe.
 *
 * Idempotent: the subscribe API merges with any existing sub (widening
 * channels, never narrowing). Multi-click on the same link is safe.
 */

import { NextRequest, NextResponse } from "next/server";
import { randomUUID } from "crypto";
import { findById, findOne, appendRow, updateById, Tables } from "@/lib/db";
import type { ParsedPolicy, RenewalSubscription } from "@/lib/types";
import { verifyToken } from "@/lib/email-token";

export const runtime = "nodejs";

const DEFAULT_DAYS_BEFORE = [60, 30, 7];
const DEFAULT_REMINDER_HOUR = 10;

interface Params {
  params: Promise<{ token: string }>;
}

export async function GET(
  request: NextRequest,
  { params }: Params
): Promise<NextResponse> {
  const { token } = await params;
  const origin = new URL(request.url).origin;

  const payload = verifyToken(token, "remind");
  if (!payload) {
    // Generic "link expired" landing — we don't tell the user whether
    // it was a bad signature vs an expired token. Both go to the same
    // page so leaking timing/state info isn't possible.
    return NextResponse.redirect(
      `${origin}/reminders/done?status=expired`,
      302
    );
  }

  const [email, parsedPolicyId] = payload.s.split("|");
  if (!email || !parsedPolicyId) {
    return NextResponse.redirect(
      `${origin}/reminders/done?status=expired`,
      302
    );
  }

  const policy = await findById<ParsedPolicy>(
    Tables.PARSED_POLICIES,
    parsedPolicyId
  );
  if (!policy || !policy.odPeriodEnd) {
    return NextResponse.redirect(
      `${origin}/reminders/done?status=not-found`,
      302
    );
  }

  // Pre-build the confirmation URL with vehicle + expiry so the
  // /reminders/done page can render the "we'll write to you before
  // 14 Jun 2026" line without a fresh DB lookup.
  const vehicleLabel =
    `${policy.vehicle?.make ?? ""} ${policy.vehicle?.model ?? ""}`.trim() ||
    "your car";
  const expiry = policy.odPeriodEnd;
  const doneUrl = new URL(`${origin}/reminders/done`);
  doneUrl.searchParams.set("vehicle", vehicleLabel);
  doneUrl.searchParams.set("date", expiry);

  try {
    const existing = await findOne<RenewalSubscription>(
      Tables.RENEWAL_SUBSCRIPTIONS,
      (s) => s.parsedPolicyId === parsedPolicyId
    );

    if (existing) {
      // Reactivate / refresh — never narrow channels, never duplicate.
      await updateById<RenewalSubscription>(
        Tables.RENEWAL_SUBSCRIPTIONS,
        existing.id,
        {
          customerEmail: email,
          status: "active",
        }
      );
      doneUrl.searchParams.set("status", "ok");
      return NextResponse.redirect(doneUrl.toString(), 302);
    }

    // Fresh subscription — email-only channels. The customer can later
    // enrich to WhatsApp via /me by adding a mobile.
    const sub: RenewalSubscription = {
      id: randomUUID(),
      parsedPolicyId,
      customerEmail: email,
      channels: ["email"],
      policyExpiryDate: expiry,
      daysBefore: DEFAULT_DAYS_BEFORE,
      reminderHourIst: DEFAULT_REMINDER_HOUR,
      status: "active",
      nudgesFired: [],
      createdAt: new Date().toISOString(),
    };
    await appendRow<RenewalSubscription>(Tables.RENEWAL_SUBSCRIPTIONS, sub);
    doneUrl.searchParams.set("status", "ok");
    return NextResponse.redirect(doneUrl.toString(), 302);
  } catch (err) {
    console.error("[reminders/click] failed to subscribe:", err);
    doneUrl.searchParams.set("status", "error");
    return NextResponse.redirect(doneUrl.toString(), 302);
  }
}
