import { notFound } from "next/navigation";
import { findById, findOne, appendRow, Tables } from "@/lib/db";
import { generateReport } from "@/lib/report-generator";
import type { ParsedPolicy, PolicyReport } from "@/lib/types";
import { ReportDisplay } from "@/components/report-display";
import { getSession } from "@/lib/session";
import { getUploadSession } from "@/lib/upload-session";

// Allow up to 60s for on-demand report generation if it wasn't pre-generated
export const maxDuration = 60;

interface PageProps {
  params: Promise<{ id: string }>;
  searchParams: Promise<{
    from?: string;
    demo?: string;
    print?: string;
    km?: string;
    drv?: string;
    oc?: string;
    pri?: string;
    /** pastClaims — captured by MidLoadQuestions during parsing. */
    pc?: string;
  }>;
}

export default async function ReportPage({ params, searchParams }: PageProps) {
  const [{ id }, sp] = await Promise.all([params, searchParams]);
  const { from, demo, print, km, drv, oc, pri, pc } = sp;
  const view: "investor" | "customer" = demo === "1" ? "investor" : "customer";
  const printMode = print === "1";

  const drivingProfile =
    km || drv || oc || pri || pc
      ? {
          annualKm: km,
          drivenBy: drv,
          otherCars: oc,
          priority: pri,
          pastClaims: pc,
        }
      : undefined;

  const parsedPolicy = await findById<ParsedPolicy>(
    Tables.PARSED_POLICIES,
    id
  );
  if (!parsedPolicy) notFound();

  let report = await findOne<PolicyReport>(
    Tables.REPORTS,
    (r) => r.parsedPolicyId === id
  );

  if (!report) {
    // First visit and report wasn't pre-generated by /api/parse (or generation failed).
    // Generate now and persist.
    console.log(`[report] No cached report for policy ${id}, generating...`);
    const start = Date.now();
    report = await generateReport(parsedPolicy);
    console.log(`[report] Generated in ${Date.now() - start}ms`);
    await appendRow<PolicyReport>(Tables.REPORTS, report);
  }

  // `from` is still accepted in the URL so the upload→report timer flow keeps
  // working, but the header no longer surfaces it (removed per design ask).
  void from;

  // Right Offer gate: customers who haven't verified their email yet
  // see the report up to the "what's missing" section, then a hard
  // gate. Investor + print mode skip the gate entirely. Customers
  // who hold either a full magic-link session OR an upload session
  // (OTP-verified email) bypass the gate too.
  const [fullSessionEmail, uploadSession] = await Promise.all([
    getSession(),
    getUploadSession(),
  ]);
  const hasVerifiedSession = !!(fullSessionEmail || uploadSession);
  const showGate = view === "customer" && !printMode && !hasVerifiedSession;

  return (
    <ReportDisplay
      parsedPolicy={parsedPolicy}
      report={report}
      view={view}
      showGate={showGate}
      drivingProfile={drivingProfile}
      printMode={printMode}
    />
  );
}
