import { notFound } from "next/navigation";
import { findById, findOne, appendRow, Tables } from "@/lib/db";
import { generateReport } from "@/lib/report-generator";
import type { ParsedPolicy, PolicyReport } from "@/lib/types";
import { ReportDisplay } from "@/components/report-display";

// Allow up to 60s for on-demand report generation if it wasn't pre-generated
export const maxDuration = 60;

interface PageProps {
  params: Promise<{ id: string }>;
}

export default async function ReportPage({ params }: PageProps) {
  const { id } = await params;

  const parsedPolicy = await findById<ParsedPolicy>(
    Tables.PARSED_POLICIES,
    id
  );
  if (!parsedPolicy) notFound();

  let report = await findOne<PolicyReport>(
    Tables.REPORTS,
    (r) => r.parsedPolicyId === id
  );

  if (!report) {
    // First visit and report wasn't pre-generated by /api/parse (or generation failed).
    // Generate now and persist.
    console.log(`[report] No cached report for policy ${id}, generating...`);
    const start = Date.now();
    report = await generateReport(parsedPolicy);
    console.log(`[report] Generated in ${Date.now() - start}ms`);
    await appendRow<PolicyReport>(Tables.REPORTS, report);
  }

  return <ReportDisplay parsedPolicy={parsedPolicy} report={report} />;
}
