/**
 * MultiDocReport — the multi-doc master report composer.
 *
 * Same template as UnifiedReport (single-doc), but in multi-doc mode:
 *
 *   1. Owner + Vehicle (from anchor doc)
 *   2. Aryan's cross-doc bottom line (synthesised across all forwarded
 *      docs, not a single doc's verdict)
 *   3. Coverage Snapshot table — multi-column mode, one column per doc
 *   4. Per-feature insights — uses the anchor doc's insights since
 *      they're the customer's "current" reference
 *   5. Things to ask — concatenated across all quote-type docs
 *   6. Annexures — each doc's existing editorial ReportDisplay rendered
 *      in sequence, replacing the old tab system
 *   7. Glossary (auto-detected across all docs)
 *   8. How we read this footer
 */

import type { ParsedPolicy, PolicyReport, ThingsToAskItem } from "@/lib/types";
import type { MultiDocComparison } from "@/lib/multi-doc-comparison";
import { BottomLineBanner } from "@/components/report-bottom-line";
import { CoverageSnapshotTable } from "@/components/report-coverage-snapshot";
import { FeatureInsightList } from "@/components/report-feature-insights";
import { ThingsToAskBlock } from "@/components/report-things-to-ask";
import { GlossarySection } from "@/components/report-glossary-section";
import { HowWeReadThisFooter } from "@/components/report-how-we-read";
import { ReportDisplay } from "@/components/report-display";

interface Props {
  comparison: MultiDocComparison;
  /** Cross-doc bottom line — pre-generated by /reports server logic
   *  before rendering, since it needs an LLM call we don't want to
   *  fire client-side. Falls back to anchor doc's bottomLine when
   *  empty. */
  crossDocBottomLine?: string;
  view: "investor" | "customer";
  showGate: boolean;
  printMode?: boolean;
}

export function MultiDocReport({
  comparison,
  crossDocBottomLine,
  view,
  showGate,
  printMode,
}: Props) {
  const { anchor, ordered, labels, table, glossaryBlob } = comparison;
  const vehicleLabel =
    `${anchor.parsed.vehicle.make} ${anchor.parsed.vehicle.model}`.trim() ||
    "your car";
  const yearLabel = anchor.parsed.vehicle.yearOfManufacture
    ? ` (${anchor.parsed.vehicle.yearOfManufacture})`
    : "";

  // Build a synthetic PolicyReport for the BottomLineBanner — uses the
  // cross-doc verdict when present; otherwise the anchor's per-doc
  // bottom line. Banner expects a PolicyReport shape, so we wrap.
  const bannerReport: PolicyReport = {
    ...anchor.report,
    bottomLine: crossDocBottomLine || anchor.report.bottomLine,
  };

  // Aggregate "Things to ask" across all quote-type docs. The single-
  // doc page only shows the active doc's questions; multi-doc shows
  // them all, grouped by insurer (the component renders them in arrival
  // order so grouping by insurer happens naturally if the customer
  // forwarded quotes from different insurers).
  const allThingsToAsk: ThingsToAskItem[] = ordered.flatMap(
    (d) => d.report.thingsToAsk ?? []
  );

  return (
    <article className="relative z-10 max-w-4xl mx-auto px-6 md:px-8 py-10 md:py-14 font-serif text-brand-charcoal">
      {/* ── 1. Owner + Vehicle anchor ─────────────────────────────── */}
      <header className="mb-8 pb-6 border-b border-brand-charcoal/15">
        <div className="font-mono text-[10.5px] uppercase tracking-[0.18em] text-brand-sage font-bold mb-3">
          · Policy comparison ·
        </div>
        <h1 className="font-serif font-medium text-3xl md:text-[40px] leading-[1.08] tracking-[-0.02em] text-brand-charcoal m-0">
          {vehicleLabel}
          <span className="italic text-brand-plum">{yearLabel}</span>
        </h1>
        <div className="mt-3 font-mono text-[10.5px] uppercase tracking-[0.14em] text-brand-slate space-y-0.5">
          {anchor.parsed.owner?.name && (
            <div>Owner · {anchor.parsed.owner.name}</div>
          )}
          <div>
            {ordered.length} {ordered.length === 1 ? "document" : "documents"}{" "}
            compared
          </div>
        </div>
      </header>

      {/* ── 2. Cross-doc bottom line ───────────────────────────────── */}
      <BottomLineBanner report={bannerReport} />

      {/* ── 3. Coverage Snapshot table (multi-column) ──────────────── */}
      <CoverageSnapshotTable
        mode="multi"
        rows={table}
        documents={labels}
        vehicleLabel={vehicleLabel}
      />

      {/* ── 4. Feature Insights (from anchor doc as the current reference) */}
      <FeatureInsightList insights={anchor.report.featureInsights} />

      {/* ── 5. Things to ask (aggregated across all quotes) ────────── */}
      <ThingsToAskBlock items={allThingsToAsk} />

      {/* ── 6. Annexures — full editorial per document ─────────────── */}
      <section className="mt-12 pt-8 border-t border-brand-charcoal/15">
        <div className="font-mono text-[10.5px] uppercase tracking-[0.18em] text-brand-sage font-bold mb-3">
          · Annexures · Detailed reports per document ·
        </div>
        <p className="font-serif italic text-[14.5px] text-brand-slate max-w-xl mb-8">
          Everything above synthesised into the comparison table. Each
          annexure below is the full audit for a single document — read
          if you want the deep version.
        </p>
        {ordered.map((doc, i) => (
          <AnnexureSection
            key={doc.parsed.id}
            label={`Annexure ${String.fromCharCode(65 + i)} — ${labels[i].label} · ${labels[i].sublabel}`}
            parsedPolicy={doc.parsed}
            report={doc.report}
            view={view}
            showGate={showGate && i === 0}
            printMode={printMode}
          />
        ))}
      </section>

      {/* ── 7. Glossary ────────────────────────────────────────────── */}
      <GlossarySection contentBlob={glossaryBlob} />

      {/* ── 8. How we read this ────────────────────────────────────── */}
      <HowWeReadThisFooter
        parsedPolicy={anchor.parsed}
        report={anchor.report}
      />
    </article>
  );
}

function AnnexureSection({
  label,
  parsedPolicy,
  report,
  view,
  showGate,
  printMode,
}: {
  label: string;
  parsedPolicy: ParsedPolicy;
  report: PolicyReport;
  view: "investor" | "customer";
  showGate: boolean;
  printMode?: boolean;
}) {
  return (
    <details className="mb-6 group" open={!printMode}>
      <summary className="cursor-pointer list-none border-l-2 border-brand-plum pl-4 py-2 hover:bg-brand-surface/40 transition-colors">
        <div className="font-mono text-[10.5px] uppercase tracking-[0.14em] text-brand-plum font-bold">
          {label}
        </div>
        <div className="font-serif italic text-[12.5px] text-brand-slate mt-0.5 group-open:hidden">
          Click to expand the detailed audit for this document.
        </div>
      </summary>
      <div className="mt-6 pl-4 border-l border-brand-charcoal/10">
        <ReportDisplay
          parsedPolicy={parsedPolicy}
          report={report}
          view={view}
          showGate={showGate}
          printMode={printMode}
        />
      </div>
    </details>
  );
}
