/**
 * HowWeReadThisFooter — small trust footer at the very bottom of every
 * report. Shows the work without bragging. Editorial signature.
 *
 * Counts come from the report's underlying data; we deliberately don't
 * fake numbers. If a field is missing, we omit that bullet rather than
 * showing a zero.
 */

import type { ParsedPolicy, PolicyReport } from "@/lib/types";

interface Props {
  parsedPolicy: ParsedPolicy;
  report: PolicyReport;
}

export function HowWeReadThisFooter({ parsedPolicy, report }: Props) {
  const generatedAt = report.generatedAt
    ? new Date(report.generatedAt).toLocaleDateString("en-IN", {
        day: "numeric",
        month: "long",
        year: "numeric",
      })
    : null;

  // Pull a handful of "what we did" data points from the report.
  // None of these are fabricated — each comes from the underlying
  // structured data.
  const gapCount = report.keyGaps?.items?.length ?? 0;
  const strengthCount = report.whatCoversWell?.items?.length ?? 0;
  const addOnsConsidered = report.addOnRecommendations?.length ?? 0;
  const tipsGiven = report.renewalTips?.items?.length ?? 0;

  const facts: string[] = [];
  facts.push(
    `Read your ${parsedPolicy.insurerName} policy line by line`
  );
  if (strengthCount > 0) {
    facts.push(`Identified ${strengthCount} ${strengthCount === 1 ? "strength" : "strengths"} in your current cover`);
  }
  if (gapCount > 0) {
    facts.push(`Flagged ${gapCount} ${gapCount === 1 ? "gap" : "gaps"} worth knowing about`);
  }
  if (addOnsConsidered > 0) {
    facts.push(
      `Evaluated ${addOnsConsidered} add-ons against your vehicle profile`
    );
  }
  if (tipsGiven > 0) {
    facts.push(
      `Wrote ${tipsGiven} renewal tips specific to your RTO`
    );
  }

  return (
    <section className="mt-10 pt-6 border-t border-brand-charcoal/15 max-w-2xl">
      <div className="font-mono text-[10.5px] uppercase tracking-[0.16em] text-brand-slate font-bold mb-2">
        · How we read this ·
      </div>
      <ul className="space-y-1.5 mb-3">
        {facts.map((f, i) => (
          <li
            key={i}
            className="font-serif italic text-[13px] text-brand-slate flex gap-2"
          >
            <span aria-hidden className="text-brand-plum">·</span>
            <span>{f}</span>
          </li>
        ))}
      </ul>
      <p className="font-serif italic text-[13px] text-brand-slate">
        {generatedAt
          ? `Audit generated ${generatedAt}.`
          : "Audit generated by Aryan."}{" "}
        Reply to this email if any of it needs a closer look — every
        reply is read and answered.
      </p>
      <p className="mt-2 font-serif italic text-[14px] text-brand-charcoal">
        &mdash; Aryan
      </p>
    </section>
  );
}
